spring:
  application:
    name: ManuscriptService
  datasource:
    url: jdbc:postgresql://localhost:5432/manuscript_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8083

